/// Flutter icons customIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
// inkscape
///
/// flutter:
///   fonts:
///    - family:  customIcons
///      fonts:
///       - asset: fonts/customIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class customIcons {
  customIcons._();

  static const _kFontFam = 'customIcons';
  static const String? _kFontPkg = null;

  static const IconData project = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData project_here = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_here = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_here = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_here = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_here = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
